yaml bug fix.

diff --git a/.github/workflows/amrex-mini-app-unit-tests-turbo-specific-containers.yaml b/.github/workflows/amrex-mini-app-unit-tests-turbo-specific-containers.yaml
--- a/.github/workflows/amrex-mini-app-unit-tests-turbo-specific-containers.yaml
+++ b/.github/workflows/amrex-mini-app-unit-tests-turbo-specific-containers.yaml
@@ -26,27 +26,27 @@ jobs:
       #    gcc --version
       #    spack --version
       - name: Modify default CI container environment after checkout
-          run: |
+        run: |
 
-            # Directory where you pulled the turbo stack repository
-            export TURBO_STACK_ROOT="${GITHUB_WORKSPACE}"
-            echo "TURBO_STACK_ROOT=${TURBO_STACK_ROOT}" >> $GITHUB_ENV
-            if [ ! -d "${TURBO_STACK_ROOT}" ]; then
-              echo "Error: TURBO_STACK_ROOT=${TURBO_STACK_ROOT} is not a valid directory."
-              exit 1
-            fi
+          # Directory where you pulled the turbo stack repository
+          export TURBO_STACK_ROOT="${GITHUB_WORKSPACE}"
+          echo "TURBO_STACK_ROOT=${TURBO_STACK_ROOT}" >> $GITHUB_ENV
+          if [ ! -d "${TURBO_STACK_ROOT}" ]; then
+            echo "Error: TURBO_STACK_ROOT=${TURBO_STACK_ROOT} is not a valid directory."
+            exit 1
+          fi
 
-            # Path to the turbo mini-app that should be within the turbo stack repository
-            export TURBO_MINI_APP_ROOT=${TURBO_STACK_ROOT}/src/amrex_mini_app
-            echo "TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT}" >> $GITHUB_ENV
-            if [ ! -d "${TURBO_MINI_APP_ROOT}" ]; then
-              echo "Error: TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT} is not a valid directory."
-              exit 1
-            fi
+          # Path to the turbo mini-app that should be within the turbo stack repository
+          export TURBO_MINI_APP_ROOT=${TURBO_STACK_ROOT}/src/amrex_mini_app
+          echo "TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT}" >> $GITHUB_ENV
+          if [ ! -d "${TURBO_MINI_APP_ROOT}" ]; then
+            echo "Error: TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT} is not a valid directory."
+            exit 1
+          fi
 
-            ## To control build and runtime behavior later
-            #export DEBUG=1
-            #echo "DEBUG=${DEBUG}" >> $GITHUB_ENV
+          ## To control build and runtime behavior later
+          #export DEBUG=1
+          #echo "DEBUG=${DEBUG}" >> $GITHUB_ENV
 
       - name: Build and Run Unit Tests
         run: |
