Break workflow into smaller actions.

diff --git a/.github/workflows/amrex-mini-app-unit-tests.yaml b/.github/workflows/amrex-mini-app-unit-tests.yaml
--- a/.github/workflows/amrex-mini-app-unit-tests.yaml
+++ b/.github/workflows/amrex-mini-app-unit-tests.yaml
@@ -69,6 +69,24 @@ jobs:
           which mpicc
           mpicc --version 2>/dev/null || true
 
+      - name: Modify default CI container environment
+        run: |
+
+          # Directory where you pulled the turbo stack repository
+          export TURBO_STACK_ROOT=$(pwd)
+
+          # Path to the turbo mini-app that should be within the turbo stack repository
+          export TURBO_MINI_APP_ROOT=${TURBO_STACK_ROOT}/src/amrex_mini_app
+          if [ ! -d "${TURBO_MINI_APP_ROOT}" ]; then
+            echo "Error: TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT} is not a valid directory."
+            exit 1
+          fi
+
+          . ${TURBO_MINI_APP_ROOT}/ncar_container_environment_variable_standardization.sh
+
+          # To control build and runtime behavior later
+          export DEBUG=1
+
       - name: Install prerequisite utilities for spack
         run: |
           dnf install -y epel-release
@@ -83,28 +101,23 @@ jobs:
           spack compiler list
           spack spec zlib # Just to test that spack is working. 
 
-      #- name: Install turbo mini-app dependencies in a spack environment
-      #  run: |
-      #    . spack/share/spack/setup-env.sh
-
-      #    echo "Building turbo spack environment:"
-
-      - name: Build and run amrex mini-app
+      - name: Install turbo mini-app dependencies in a spack environment
         run: |
-
 
           . spack/share/spack/setup-env.sh
 
-          export TURBO_STACK_ROOT=$(pwd)
-          export DEBUG=1
-          export DOXYGEN=0
+          . ${TURBO_MINI_APP_ROOT}/create_spack_environment.sh
 
-          mini_app_root=${TURBO_STACK_ROOT}/src/amrex_mini_app
+          if [ -z "$SPACK_ENVIRONMENT_NAME" ]; then
+            echo "Error: SPACK_ENVIRONMENT_NAME is not set."
+            exit 1
+          fi
 
-          . ${mini_app_root}/ncar_container_environment_variable_standardization.sh
+      - name: Build and run turbo amrex mini-app
+        run: |
 
-          . ${mini_app_root}/create_spack_environment.sh
+          . spack/share/spack/setup-env.sh
 
           spack env activate $SPACK_ENVIRONMENT_NAME
 
-          ${mini_app_root}/build_and_run.sh
+          ${TURBO_MINI_APP_ROOT}/build_and_run.sh
